# Эта настройка перенаправляет все запросы, которые не являются файлами,
# на index.html. Это позволяет React Router обрабатывать роутинг.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200